version: '3.8'

services:
  app1:
    image: vitorjdev/http-helloworld
    ports:
      - "8081:80"
    environment:
      - APP_INSTANCE_NAME=INSTANCE_1
    networks:
      - apps-network
  app2:
    image: vitorjdev/http-helloworld
    ports:
      - 8082:80
    environment:
      - APP_INSTANCE_NAME=INSTANCE_2
    networks:
      - apps-network
  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - apps-network

networks:
  apps-network:
    driver: bridge